---
- name: Create the 'vm-admin' RoleBinding
  hosts: utility
  gather_facts: false

  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"

  vars:
    group_name: database-admins
    namespaces:
      - development-db
      - staging-db

  tasks:

    - name: "Verify that the group exists: '{{ group_name }}'"
      kubernetes.core.k8s_info:
        api_version: user.openshift.io/v1
        kind: Group
        name: "{{ group_name }}"
        wait: false
      register: result_group
