---
- name: Patch cluster proxy
  hosts: utility
  gather_facts: false

  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"
      wait: true
      wait_sleep: "{{ wait_sleep }}"
      wait_timeout: "{{ wait_timeout }}"

  vars:
    operator: "{{ operators['nmo'] }}"
    namespace: "{{ operator['namespace']['name'] }}"
    label_selector: "{{ operator['label_selector'] }}"

  tasks:

    - name: Patch cluster proxy
      kubernetes.core.k8s:
        state: patched
        kind: "{{ item.kind }}"
        name: "{{ item.metadata.name }}"
        definition: "{{ item }}"
      # retries: "{{ retries_num }}"
      # delay: "{{ delay_num }}"
      register: result
      loop_control:
        label: "{{ item.kind }}/{{ item.apiVersion }}"
      loop:

        - apiVersion: config.openshift.io/v1
          kind: Proxy
          metadata:
            name: cluster
          spec:
            trustedCA:
              name: ""
