---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datavolume-cloner
rules:
  - apiGroups:
      - "cdi.kubevirt.io"
    resources:
      - "datavolumes/source"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-to-user
  namespace: vm-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datavolume-cloner
subjects:
  - kind: ServiceAccount
    # apiGroup: v1
    name: default
    namespace: development-db
  - kind: ServiceAccount
    # apiGroup: v1
    name: default
    namespace: staging-db
