---
- name: Confirm node are active
  hosts: utility
  gather_facts: false

  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"
      wait: true
      wait_sleep: "{{ wait_sleep }}"
      wait_timeout: "{{ wait_timeout }}"

  tasks:

    - name: Check nodes
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Node
        name: "{{ item }}"
        wait_condition:
          type: Ready
          status: "True"
      # retries: "{{ retries_num }}"
      # delay: "{{ delay_num }}"
      register: check_nodes
      # loop: "{{ all_nodes }}"
      loop: "{{ nodes }}"
