---
- name: Uncordon nodes
  hosts: utility
  gather_facts: false

  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"

  tasks:

    - name: Mark nodes as schedulable (uncordon)
      kubernetes.core.k8s_drain:
        state: uncordon
        name: "{{ item }}"
      register: nodes_uncordon
      loop: "{{ nodes }}"
