---
- name: Revert worker node settings and labels
  hosts: utility
  gather_facts: false

  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"

  vars:
    node_label: external-network
    worker_nodes:
      - worker01
      - worker02

  tasks:

    - name: Set 'br1' to absent
      kubernetes.core.k8s:
        state: present
        wait: true
        wait_condition:
          type: Available
          status: "True"
        inline:
          apiVersion: nmstate.io/v1
          kind: NodeNetworkConfigurationPolicy
          metadata:
            name: remove-br1-ens4-policy
          spec:
            nodeSelector:
              external-network: "true"
            desiredState:
              interfaces:
                - name: br1
                  description: Linux bridge with ens4 as a port
                  type: linux-bridge
                  state: absent
                  ipv4:
                    dhcp: true
                    enabled: true
                  bridge:
                    options:
                      stp:
                        enabled: false
                      port:
                        - name: ens4
                - name: ens4
                  type: ethernet
                  state: up
                  mtu: 1500
                  ipv4:
                    auto-dns: true
                    auto-gateway: true
                    auto-route-table-id: 0
                    auto-routes: true
                    dhcp: true
                    enabled: true
                  ipv6:
                    auto-dns: true
                    auto-gateway: true
                    auto-route-table-id: 0
                    auto-routes: true
                    autoconf: true
                    dhcp: true
                    enabled: true
                  lldp:
                    enabled: false

    # # FIXME: Convert to 'kubernetes.core.k8s'
    # - name: "Ensure the worker nodes do not have the label: '{{ node_label }}'"
    #   ansible.builtin.command:
    #     cmd: "oc label node {{ item }} {{ node_label }}-"
    #   ignore_errors: true
    #   loop: "{{ worker_nodes }}"

    - name: "Ensure the nodes do not have the label: '{{ node_label }}'"
      kubernetes.core.k8s:
        state: patched
        api_version: v1
        kind: Node
        name: "{{ item }}"
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            labels:
              "{{ label }}": NULL
      loop: "{{ worker_nodes }}"
      diff: true

    - name: "Remove label from nodes: '{{ node_label }}'"
      kubernetes.core.k8s:
        state: present
        api_version: v1
        kind: Node
        name: "{{ item }}"
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            labels:
              "{{ label }}": NULL
      loop: "{{ worker_nodes }}"
      diff: true

    # # FIXME: Convert to 'kubernetes.core.k8s'
    # - name: Remove NodeNetworkConfigurationPolicy if exists
    #   ansible.builtin.command:
    #     cmd: "oc delete NodeNetworkConfigurationPolicy {{ item }} --ignore-not-found --wait"
    #   ignore_errors: true
    #   loop:
    #     - br1-ens4-policy
    #     - remove-br1-ens4-policy

    - name: Delete NNCP if exists
      kubernetes.core.k8s:
        state: absent
        api_version: nmstate.io/v1
        kind: NodeNetworkConfigurationPolicy
        name: "{{ item }}"
        wait: true
      loop:
        - br1-ens4-policy
        - remove-br1-ens4-policy
