---
# NOTE: This playbook requires that the following playbooks run BEFORE via the lab script
# - playbooks/deploy-virtctl.yml

- name: Create namespace and data volume
  hosts: utility
  gather_facts: false

  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"

  vars:
    vm_qcow2: rhel9-mariadb.qcow2
    vm2_qcow2: rhel9-helloworld.qcow2
    dv_name: mariadb-server
    dv2_name: web-server
    dv_namespace: template-review
    dv_access_mode: ReadWriteMany
    dv_size: 10Gi

  tasks:
    - name: "Ensure that the project exists: {{ dv_namespace }}"
      kubernetes.core.k8s:
        state: present
        inline:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ dv_namespace }}"

    - name: Create DV for 'mariadb-server'
      kubernetes.core.k8s:
        state: present
        inline:
          apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: "{{ dv_name }}"
            namespace: "{{ dv_namespace }}"
          spec:
            source:
              http:
                url: "{{ utility_url }}{{ vm_qcow2 }}"
            pvc:
              accessModes:
                - "{{ dv_access_mode }}"
              volumeMode: "{{ dv_sc_mode }}"
              resources:
                requests:
                  storage: "{{ dv_size }}"
              storageClassName: "{{ dv_sc_name }}"
        wait: true
        wait_condition:
          type: Ready
          status: "True"
        wait_sleep: "{{ wait_sleep }}"
        wait_timeout: "{{ wait_timeout }}"

    - name: Create DV for 'web-server'
      kubernetes.core.k8s:
        state: present
        inline:
          apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: "{{ dv2_name }}"
            namespace: "{{ dv_namespace }}"
          spec:
            source:
              http:
                url: "{{ utility_url }}{{ vm2_qcow2 }}"
            pvc:
              accessModes:
                - "{{ dv_access_mode }}"
              volumeMode: "{{ dv_sc_mode }}"
              resources:
                requests:
                  storage: "{{ dv_size }}"
              storageClassName: "{{ dv_sc_name }}"
        wait: true
        wait_condition:
          type: Ready
          status: "True"
        wait_sleep: "{{ wait_sleep }}"
        wait_timeout: "{{ wait_timeout }}"
